### ISSUE TITLE
Addon preview popup - Closing cross hover

### ISSUE THREAD

**Issue by WybeBosch** [jliddev/WowUp#286]
Hey there, minor nit pick, easy fix. 
When you have opened a Preview Popup for an addon in the client, 
when hovering over the Cross that closes the popup, the mouse doesnt turn into a "hand" symbol indicating that its clickable. 

![image](https://user-images.githubusercontent.com/40889930/97777382-1b1b6780-1b70-11eb-98a5-3aa861bdb358.png)

Think this is mostly just something that was missed to add, and should hopefully be an easy fix ! :)

(Probably not exactly like this since you are using a framework, but you get the point ! )

```css
mat-icon.mat-icon.notranslate.close-icon.mat-primary.material-icons {
    cursor: pointer;
}
```
